export const projects = [
  {
    title: 'stepby',
    description: "StartUp project, a small team of juniors working as a strong team to accomplish this project!!!",
    image: '/images/stepby.png',
    tags: ['React', 'Team Work', 'NodeJS', 'ExpressJS', 'AWS-S3', 'MongoDB'],
    source: [''],
    visit: '',
    id: 0,
  },
  {
    title: 'My Portfolio',
    description: "Exploring more deep in this amazing field, Design!!! Sass, animations, loaders... was very nice playing!!!",
    image: '/images/myPortfolio.png',
    tags: ['React', 'Sass'],
    source: ['https://github.com/ShaulAttie/my_portfolio'],
    visit: 'https://my-portfolio-sa.netlify.app/',
    id: 1,
  },
  {
    title: 'MusicPlyr',
    description: "MERN + Redux, this playlist is making my life easier, no more ads!!!\nAhhhh, also playing with Sass animation.",
    image: '/images/playlist.png',
    tags: ['React', 'Redux', 'NodeJS', 'ExpressJS', 'MongoDB'],
    source: ['https://github.com/ShaulAttie/Playlist-Client', 'https://github.com/ShaulAttie/Playlist-Server'],
    visit: 'https://musicplyr13.netlify.app/',
    id: 2,
  },
  {
    title: 'Memories',
    description: "My first time plying with Redux, a small social media platform to share your most special memories, was a great adventure.",
    image: '/images/memories.png',
    tags: ['React', 'Redux', 'NodeJS', 'ExpressJS', 'MongoDB'],
    source: ['https://github.com/ShaulAttie/my-memories_client_final', 'https://github.com/ShaulAttie/My_Memories_Server'],
    visit: 'https://my-memories13.netlify.app/',
    id: 3,
  },
  {
    title: 'ReadMate',
    description: "Boot Camp Project (from a StartUp), amazing app to help us to improve reading. Very nice experience!!!",
    image: '/images/readmate.png',
    tags: ['React', 'Team Work', 'NodeJS', 'ExpressJS'],
    source: [''],
    visit: '',
    id: 4,
  },
  {
    title: 'Fake Store',
    description: "Fake Store, there are a lot of them in the internet, doing it with TypeScript was The Challenge.\nTypeScript, what a language!!!",
    image: '/images/fakeStore.png',
    tags: ['React', 'TypeScript'],
    source: ['https://github.com/ShaulAttie/FakeStore_TS'],
    visit: 'https://fakestore-ts.netlify.app/',
    id: 5,
  },
  {
    title: 'Countries',
    description: 'I believe that this was my first React app, also my first API. How they say,"The first time we never forget!" The rest was history. ',
    image: '/images/countries.png',
    tags: ['React'],
    source: ['https://github.com/ShaulAttie/Country_API'],
    visit: 'https://google.com',
    id: 6,
  },
  {
    title: 'Memory Card Game',
    description: "My first JavaScript Project. I remember how hard was it.\nToday i'm proud for it!!!",
    image: '/images/memoryCard.png',
    tags: ['Vanilla JavaScript'],
    source: ['https://github.com/ShaulAttie/MemoryCard-Game'],
    visit: 'https://memorycard-js.netlify.app/',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];