export const projects = [
  {
    title: 'Memories',
    description: "My first time plying with Redux, a small social media platform to share your most special memories, was a great adventure.",
    image: '/images/memories.png',
    tags: ['React', 'Redux', 'NodeJS', 'ExpressJS', 'MongoDB'],
    source: ['https://github.com/ShaulAttie/my-memories_client_final', 'https://github.com/ShaulAttie/My_Memories_Server'],
    visit: 'https://my-memories13.netlify.app/',
    id: 0,
  },
  {
    title: 'MusicPlyr',
    description: "MERN + Redux (again), this playlist is making my life easier, no more ads!!!\nAhhhh, also playing with Sass animation.",
    image: '/images/playlist.png',
    tags: ['React', 'Redux', 'NodeJS', 'ExpressJS', 'MongoDB'],
    source: ['https://github.com/ShaulAttie/Playlist-Client','https://github.com/ShaulAttie/Playlist-Server'],
    visit: 'https://musicplyr13.netlify.app/',
    id: 1,
  },
  {
    title: 'Memory Card Game',
    description: "My first JavaScript Project. I remember how hard was it.\nToday i'm proud for it!!!",
    image: '/images/memoryCard.png',
    tags: ['Vanilla JavaScript'],
    source: ['https://github.com/ShaulAttie/MemoryCard-Game'],
    visit: 'https://memorycard-js.netlify.app/',
    id: 2,
  },
  {
    title: 'My Portfolio',
    description: "Exploring more deep in this amazing field, Design!!! Sass, animations, loaders... was very nice playing!!!",
    image: '/images/myPortfolio.png',
    tags: ['React', 'Sass'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Memory Card Game',
    description: "A small social media platform to share your more special memories. My first time plying with Redux. was a great adventure.",
    image: '../../assets/images/projects/proj01.png',
    tags: ['React', 'Redux', 'NodeJS', 'MongoDB', 'ExpressJS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
  {
    title: 'Countries',
    description: "While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: '../../assets/images/projects/proj02.png',
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 5,
  },
  {
    title: 'WebRTC App',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
    image: '../../assets/images/projects/proj03.png',
    tags: ['React', 'WebRTC'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 6,
  },
  {
    title: 'Unichat',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '../../assets/images/projects/proj04.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];